### ISSUE TITLE
Road-map for post-processing tools (myrmidon/FORT Studio)

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/myrmidon#184]
In order to accommodate future needs for Keller's group projects, we propose the following changes to the post-processing tools, i.e. FORT Studio and the myrmidon API.

### Motivations

The current software distribution infrastructure, based on the APT repository hosted at https://packages.tuleu.science suffers from the following inconveniences:

 * **Maintenance of Debian packages of C++ libraries is not easy at all for non tech-savvy users.** Knowing which packages to install, update, and remove in case of conflict is complex, and therefore there is a huge need for end-user support.
 * **User are required to manually enforce binary compatibility between C++ and R bindings version**. This is a short coming from using C++, Application Binary Interface (ABI) is easily broken by little changes, and to maintain compatibility, it is asked to the user to update its R binding accordingly. Often they don't, and in best case they get a compilation error and asked about it, or in worse case scenario, they don't and silently their installation is broken.
 * **Users does not update FORT Studio regularly**. For FORT Studio people are not updating their software regularly, and help is asked about bugs fixed almost 6 month ago.
 * **Users have no control with the version they use of the myrmidon API**. Repeatability of experiment is now a must in scientific data analysis. Therefore one must be able for re-running an experiment to be able to pick an old, even buggy version of myrmidon to run or re-run some analysis. It is very tedious for both the package maintainer and the user to achieve this with Debian packages and apt repository as they always enforce you to use the latest published version of the packages. This is good for GUI application like FORT Studio or a web browser. This is bad for a scientific oriented package like myrmidon.
 * **Debian packaging maintenance is a very technical task with a steep learning curve**. Well package distribution is always
   difficult and very technical, Debian way of solving this is even more difficult. More modern tools may let you make things a
   little bit more dirty but are easier to work with. Since I am the only person at the moment with Debian packaging skills in the 
  team, it forces a bottleneck. Also putting automatic Debian packaging building in a Continuous Integration environment, does 
  not comes with pre-made tools - you have to make and maintain your own scripts for that. However more modern solution can 
  be more easily put in an CI environment.
 * **Distribution over packages.tuleu.science is not reliable**. This website is tied to a personal server and I do not intend to ensure its availability for any point in time in the future. This server is a good thing for development as I can quickly setup a web server, a reverse proxy or an APT repository, but certainly not for production, as the OVH incident has shown. I cannot ensure and will not ensure its availability. For example, if OVH would increase its maintenance cost in the future, I am not certain I would like to pay for this service personally. I think that it is far past the time for the FORT project to have its own infrastructure, hosted or paid by an institution.

### Proposition

To circumvent the inconveniences mentioned above we propose the following changes to the distribution:

* **Myrmidon and the different bindings** will be packaged with conda/anaconda. [Anaconda](https://anaconda.com) is a language agnostic package and environment manager. Therefore it can be used to package myrmidon C++ library with exact dependencies management, independent of the libraries installed with your distribution. It allows you to create environment, allowing you for example to have one environment when you develop new tools with the latest myrmidon version, and for a ongoing or old experiment, to keep and maintain an environment with an exact older version of myrmidon so you can replicate your experiment, even with all the quirks and bugs of that version.
* **FORT Studio to be distributed with snap**. This tool has been  proven extremely handful to distribute `fort-scanner`, `leto-cli`
  and `zeus-cli`. It is easier to develop with, comes with automatic  and it is easy to distribute stable/beta/candidate/edges
  releases. No need to modify your APT sources file for that.

But wait, is this model broken If I do not want to always use the latest myrmidon version? Maybe the latest version of studio will produce a `.myrmdion` file which is not compatible with an older myrmidon version.

In future development of Studio we will try at all cost to avoid this situation. However it may not be possible to do so for ever. For that use case, studio will also be packaged with conda. However you will need to launch it from the command line from the right environment, or use the Anaconda navigator. The snap will actually be a repackage of the anaconda environment pointing the latest FORT Studio with integration in the system menus, all of this independant of any conda installation on the user system.

### Implication for end-user.

You would need to learn how to use conda/anaconda/miniconda . The FORT project will distribute conda ready package for the C++ library, R bindings, FORT Studio in conda. There is no choice of the distribution method yet (an anaconda channel or conda-forge) but users would need to become familiar with these tools and the concept of environment and channels. Debian packages would need to be removed.

## 2. Python bindings and myrmidon API rewrite

Keller's group needs python bindings to the myrmidon API for their future usage. Due to some technical issue, this will imply some changes on the myrmidon API that will becomes simpler. This would also results in breaking changes in the R bindings. Since there will be some breaking changes introduced, I propose to go a little bit further and makes the R bindings less C++ like but with a more R feeling

* **Remove of const access API** const access is nice in a C++ environment, but it makes things overly complicated in other languages such as C,R or go: there is no const object, so we need to have theses C**** object with less methods to emulate const objects. The myrmidon API will become RW only, with only object with plain access.
* **Simplification of time object**. Internally, myrmidon represents Time with complex object that ensure a greater precision and avoids leap second issue in most use case. But you need to manipulate these weird `fmTime` objects. Now in the API which are not C++ (python, R or any others) the bindings will for simplicity translate these object to plain date time object for that language. Indeed, by its architecture, the object returned by queries will not suffers from the issue of leap seconds s they will use the myrmidon's internal time object, but represents sequence of time by a time object and offsets in seconds from that reference time. So will keep those complex `fmTime`, `fmTimeCPtr` object out from the user. But not in C++, because time utilities are still a joke IMHO.
* **Move to a C style Object-Oriented (OO) API in R**. When I read in 2020 that R has support for object oriented programming through S3/S4 classes, I was pleased as I thought it would require less work to develop bindings for a C++ API. I was wrong, and their support in the standard development tools, documentation generation, is quite insufficient IMHO. Furthermore most user are not used to plain OO paradigm. Therefore I propose to rewrite them to use a C style OO API, which only uses function. For example getting all ants in an experiment will change from
```R
e <- fmExperimentOpen('foo.myrmidon')
antsAsList <- e$ants()$objects
```
To a C style API
```R
e <-fmExperimentOpen('foo.myrmidon')
antsAsList <- fmExperimentAnts(e)$objects // $objects is needed as fmExperimentAnts() returns a pair of a summary data.frame and a list of objects
```
By convention looking in  the documentation for any function that are at the `fmExperiment` level (in OO words, the methods of an `fmExperiment` object), will be to look in the documentation to all methods starting with `fmExperiment*`.

**Comment by nathaliestroeymeyt** [comment]
Hi, I've read the road-map, it all looks quite sensible to me. I only have one question related to the statement "You would need to learn how to use conda/anaconda/miniconda". Most end-users are biologists whose programming knowledge is limited to a bit of R and/or python, so what may seem very simple to you and Matthias may be actually quite tricky/alien for us... So I guess my question is: how complicated is conda/anaconda/miniconda - and would we need it only at the installation step, or whenever we need to run fort-studio / analyse data in R?

**Comment by atuleu** [comment]
conda is an environment manager which means its purpose is to help the user to install different specific version in different environment, and choose from which environment to use a perticular software. For example you could install R 3.6 and R 4.0 and a bunch of other software on a computer and choose which one to use for a given analysis.

Anaconda gives example on how to install R package from anaconda: https://docs.anaconda.com/anaconda/packages/r-language-pkg-docs/ . It also have documentation on how to use Rstudio and R packages with an anaconda environment: https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/

**Comment by EnricoGavagnin** [comment]
Hi, I have read the road-map. I am excited about the python bindings.

**Comment by dschlaeppi** [comment]
+1

**Comment by atuleu** [comment]
Migration to `conda` / `snap` fully operational as of v0.7.3
