### ISSUE TITLE
[r-fort-myrmidon] Package conflict with raw miniconda installation

### ISSUE THREAD

**Issue by EnricoGavagnin** [formicidae-tracker/myrmidon#192]
I followed the guide to remove the Debian packages and APT listing of packages.tuleu.science, but I am getting the following package conflicts when running "conda install -c formicidae-tracker r-fort-myrmidon":

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package xz conflicts for:
r-fort-myrmidon -> r-base[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<6.0a0']
python=3.8 -> xz[version='>=5.2.4,<6.0a0|>=5.2.5,<6.0a0']

Package libgcc-ng conflicts for:
r-fort-myrmidon -> libgcc-ng[version='>=9.3.0']
r-fort-myrmidon -> r-rcpp -> libgcc-ng[version='7.2.0.*|>=7.2.0|>=7.3.0']

Package libstdcxx-ng conflicts for:
r-fort-myrmidon -> libstdcxx-ng[version='>=9.3.0']
r-fort-myrmidon -> r-rcpp -> libstdcxx-ng[version='7.2.0.*|>=7.2.0|>=7.3.0']

**Comment by atuleu** [comment]
From the log, I see ypu are using an environment with python 3.8. Currently fort-myrmidon is build against python 3.9 . Could you try the same from a fresh environment ?

**Comment by EnricoGavagnin** [comment]
Done, I still get this:

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ncurses conflicts for:
python=3.9 -> ncurses[version='>=6.2,<7.0a0']
python=3.9 -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.1,<7.0a0']

Package libgcc-ng conflicts for:
python=3.9 -> libgcc-ng[version='>=7.3.0']
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']

Package tk conflicts for:
r-fort-myrmidon -> r-base[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.8,<8.7.0a0']
python=3.9 -> tk[version='>=8.6.10,<8.7.0a0']

**Comment by EnricoGavagnin** [comment]
I see, I was using conda 3, I will update and try agian. Thank you!

**Comment by EnricoGavagnin** [comment]
Sorry I checked and I actually have conda 4.10.1 - would that be a problem? Should I downgrade to 4.10.0?

**Comment by atuleu** [comment]
So it is an oversight from the documentation. However I still don't know if the best would be for me to do some light repackaging and only use the `defaults` channel. If you want to try it right know, you need to source the conda-forge channel before installing r-fort-myrmidon. Just do once `conda config --add channels conda-forge`. Then the installation will be able to find a packaging solution.

**Comment by EnricoGavagnin** [comment]
Ok that makes sense. It worked after sourcing the conda-forge. Thnaks a lot

**Comment by atuleu** [comment]
I prefer to leave this open, as maybe the solution would be not to use `conda-forge` anymore. Or if `conda-forge` is unevitable, the documentation should mention it accordingly

**Comment by atuleu** [comment]
@AdrianoWanderlingh I think you are using a full anaconda installation. Would you try miniconda, which comes with less package pre installed ?
 To remove anaconda, simply remove your ~/anaconda3` directory.

**Comment by AdrianoWanderlingh** [comment]
Removed anaconda, installed miniconda and re-run the package installation of all the 3 packages successfully.
I tried to open the fort-studio executable from the GUI but it was reporting a problem with the installer not being included in the shared library files, this is the output when trying from terminal:

```
(base) cf19810@IT068980:~$ fort-studio
fort-studio: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory

```

**Comment by atuleu** [comment]
Two points here:
* preferred method for installing and using `fort-studio` is through `snap`. If you install both the `snap` package and the `conda` package I am not sure which version will be selected when you use it on the command-line. However the `snap` package install a `FORmicidae Tracker Studio` menu entry. So it is preferable not to use the command-line anymore to start `fort-studio`, but use the system menus.
* It is a quite bad practice to install any packages in the `base` environment of conda. Please always create and activate a dedicated environment for using `r-fort-myrmidon`. You may otherwisse run in a lot of problem down the line. Please refer to the [conda documentation](https://conda.io/projects/conda/en/latest/user-guide/concepts/environments.html). I would also suggest to disable the [base environment](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#conda-init)

**Comment by atuleu** [comment]
@AdrianoWanderlingh  : I moved your last issue to a new one:  #194

**Comment by AdrianoWanderlingh** [comment]
the reason why I went through the conda version is that, as suggested here https://github.com/formicidae-tracker/myrmidon/blob/master/guides/remove_debian_package.md , that's the way to go for R users (and I will need to use the Rbindings).

**Comment by atuleu** [comment]
You need to use `conda` for the `r-fort-myrmidon` package, as they are now only distributed through `conda`. However you do not need to install `fort-studio` package through `conda`, but should rather use `snap` as it is mentionned in the documentation. `fort-studio` conda package is only here for archiving purpose. For example to  install  a specific version of `fort-studio` for replicating exactly an experiment in 4 years from now. So in quite almost all case you want the `snap` distribution of fort-studio to use as a daily tool. You can easily remove the `fort-studio` package from your conda environment with `conda remove fort-studio` it will not remove the `r-fort-myrmidon` package that install the C++ library and the bindings in your conda environment.  


`conda` will ensure that the installed `libfort-myrmidon` and `r-fort-myrmidon` packages are always compatible which each other, and will never be updated implicitly. For example, if a new version will come with quite some breaking changes, I will not be updated, leaving you with the control of when to update them and update your R script accordingly. On the other hand `fort-studio` will always be kept to the last version by `snap` allowing to benefit of the latest bug fixes.
