### ISSUE TITLE
Command to access removable media in guide does not work

### ISSUE THREAD

**Issue by dschlaeppi** [formicidae-tracker/myrmidon#195]
I just installed fort-studio with snap on a laptop and need to access removable media (external hard drive). However, copy-pasting the command to access removable media from the guide (https://github.com/formicidae-tracker/myrmidon) does not work for me. 

sudo connect fort-studio:removable-media :removable-media`  (as it is in the guide) 
When running this, '>' is displayed in the terminal indicating that it might need more input and thus nothing happens
if I run it without the ' in the end it says "sudo: connect: command not found".

What am I missing?

**Comment by atuleu** [comment]
Yes it is an error in the documentation. It is the subcommand `connect` from the the `snap` executable. The right command is `sudo snap connect .........`

**Comment by dschlaeppi** [comment]
Perfect, that worked. Thank you very much.
