### ISSUE TITLE
API proposition for matching Movie frame and TrackingData

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/myrmidon#197]
As of v0.7, the only public API endpoint to match a given movie frame to tracking data is the method `fort::myrmidon::Space::LocateMovieFrame` ( [see its documentation](https://formicidae-tracker.github.io/myrmidon/docs/latest/api/#fort::myrmidon::Space/fort::myrmidon::Space::LocateMovieFrame) ). This for a given Time returns a given movie file path and frame number. Using the exact frame time, one can therefore match an `fort::myrmidon::IdentifiedFrame` or a `fort::myrmidon::CollisionFrame` to a movie frame. In case there was no tracking frame drop and no video frame drop, this interface is sufficient to infer a 1:1 relation between the result of a `fort::myrmidon::Query::IdentifyFrame` call between two time and two call to `fort::myrmidon::Space::LocateMovieFrame` with the same times. However if there is any tracking frame drop or movie frame drop (there was sufficient CPU time to track the data, but not enough to encode the frame), this simple relation does not hold, and the only way for a user to access this information would be to query for each frame Time `LocateMovieFrame`. This has two major drawback: we ask the user to build some careful check to handle movie frame drop, and this is extremly inefficient as we will make consecutive random access to tracking file, so at each of these call, a tracking data file is opened, part of it read, and then closed.

So I would like to propose a new API endpoint to facilitate the mapping of video to movie frame. I imagine at the moment several solutions:
1. **Add an option to `fort::myrmidon::Query::identifyFrame` to return the matching movie frame file and frame number or absence of.** : The benefit is that it is the most efficient way to make this matching, as while we are reading the tracking data file, we are also matching frame. It would be optional as it will have a non negligible memory footprint for large queries, and therefore it is most likely preferable to only get this data when actually needed (for exporting an annotated movie file for example), and not when performing heavy data analysis. The drawback is, when you want to lay out ant trajectories, you will have to make two requests, one for the trajectories, and one for the positions and frame-matching
2. **Making a dedicated query `fort::myrmidon::Query::MatchMovieFrame` that for two Time, will return a list of all movie file and movie frame number, and the corresponding tracking data time, if it exitts.** Then the user will do the corresponding other Query he needs, and will use Time to make exact match between its Query and the corresponding movie frame. Since all results are Time ordered. this is just skipping a few frame when some Tracking data frame drops did occurs.
3. **A mix of the two: add an option for each queries to also return the list of movie frame correspondances**. Then the frame matching could be efficiently implemented for each queries.

The major pro and cons of each solutions:
 * 1, and 3. make sure we do not scan all tracking data twice.
 * 2. in my opinion gives user more control to diagnose when a movie frame drop or a tracking frame drop did occur in the dataset. Could also be a drawback because we will ask a bit more work from the user.
 * 2. lets the API be simpler, as Query already have a lot of parameter, and fields
 * 3. suffers that the implementation will not be so easy, quite complex, and will make the code base even harder to debug
 * 2. is less efficient as the tracking dataset will be parsed twice in any realistic scenario.

**Comment by atuleu** [comment]
Also some post scriptum comment : the fact that making two different query and therefore parsing of the tracking data, can be leveraged. We can make the  hypothesis that in most cases, this frame queries will be used to annotate a short movie segment of a few minutes to a few hours to build a nice illustration video, and not weeks of tracking data in one shot. Then the overhead of parsing the data twice is negligible.

**Comment by matthiasruegg** [comment]
I currently don't see a common data analysis scenario in which specific frames have to be addressed repetitively and therefore no necessity for an efficient Query. I therefore vote for number 1. As far as I understand, option 1 is also the easiest to implement, because of its "hit or miss" behavior. I think it is perfectly fine.

**Comment by atuleu** [comment]
In fact number 2 would be the simplest, as we do not have to add fields to `fort::myrmidon::IdentifiedFrame` objects, and I do not have to change code in existing queries. But the least efficient as data will be parsed twice. But it will be easier to detect video frame without any tracking data.

**Comment by atuleu** [comment]
to illustrate the difference between the two API

first scenario:
```c++
auto e = fort::myrmidon::Experiment::Open("tada.myrmidon");
auto identified = fort::myrmidon::Query::IdentifiyFrames(e,start,end); // note: option to report movie frame on.
std::string moviePath;
cv::VideoCapture movie;
int64_t lastMovieFrameNumber = -1;
for( const auto & f : identified ) {
  // if file is not opened, or we need to open a new video file segment.
  if ( moviePath != identified->MoviePath) {
    moviePath= identified->MoviePath;
    lastMovieFrameNumber = identified->MovieFrameNumber - 1;
    movie = cv::VideoCapture(moviePath);
    movie.set(CV_VIDEO_FRAME_POS,identified->MovieFrameNumber);
  }
  cv::Mat frame;
  while(identified->MovieFrameNumber - lastMovieFrameNumber > 1 ) {
    movie >> frame;
    lastMovieFrameNumber++;
    std;:cerr << "no tracking data for frame " << lastMovieFrameNumber << " skiping it" << std::endl;
  }
  movie >> frame;
  lastMovieFrameNumber++;
  // identified and frame are at the same time from here
}
```

or in the second case:
 
```c++
auto e = fort::myrmidon::Experiment::Open("tada.myrmidon");
auto identified = fort::myrmidon::Query::IdentifiyFrames(e,start,end); // note: option to report movie frame on.
auto movieFrames = fort::myrmidon::Query::MatchMovieFrame(e,start,end);
std::string moviePath;
cv::VideoCapture movie;
int64_t lastMovieFrameNumber = -1;
auto iter = identified.begin();
for ( const auto & movieFrame : movieFrames ) {
  // if file is not opened, or we need to open a new video file segment.
  if ( moviePath != movieFrame.Path ) {
    moviePath= movieFrame.Path;
    lastMovieFrameNumber = movieFrame.FrameNumber - 1;
    movie = cv::VideoCapture(movieFrame.Path);
    movie.set(CV_VIDEO_FRAME_POS,movieFrame.FrameNumber);
  }
  while( (*iter)->FrameTime < movieFrame.Time ) {
    // we skip all tracking frame without a video frame
    ++iter
  }
  if ( (*iter)->FrameTime > movieFrame.Time ) {
    // a movie frame without any tracking data
  } else {
    // a movie frame with tracking data.
  }
}
```

I feel the second style is much more clearer.

**Comment by matthiasruegg** [comment]
Yes the second is more intuitive for me: Iterate over available movie frames and check if those frames have identifications. It also matches better the use case of creating a video overlay with some tracking data.For such visualization processes, one would most likely still want to keep movie frames in a video that have no identification, so this is simpler. I vote for the second then.
