### ISSUE TITLE
Issues installing libfort-myrmidon and r-fort-myrmidon with conda

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/myrmidon#198]
Hello,
I am trying to install the latest versions of the R bindings with conda/anaconda, but I am experiencing issues.

I believe I have configured conda properly: I have created a new environment with R and RStudio installed, I have activated it; I have added formicidae-tracker and conda-forge to my channels; and I have followed the official conda-forge instructions to ensure that conda-forge is at the top of the priority list with a strict priority.

With all this done, I tried to install libfort-myrmidon and r-fort-myrmidon in my environment. I tried in two ways: first via the anaconda-navigator, and when this failed I tried with the command line.

In both cases the installation seems to hang forever in the "Solving environment" step, and so does not install the packages.

Below is a copy of my attempt via command line (still stuck on the Solving environment step as we speak).

I am a complete beginner with conda so could easily have done something wrong - any help would be welcome!

(base) bzniks@LinuxMint:~$ conda activate /home/bzniks/anaconda3/envs/RStudio_May2021/
(RStudio_May2021) bzniks@LinuxMint:~$ conda config --add channels formicidae-tracker
(RStudio_May2021) bzniks@LinuxMint:~$ conda info

     active environment : RStudio_May2021
    active env location : /home/bzniks/anaconda3/envs/RStudio_May2021
            shell level : 2
       user config file : /home/bzniks/.condarc
 populated config files : /home/bzniks/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/bzniks/anaconda3  (writable)
      conda av data dir : /home/bzniks/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/formicidae-tracker/linux-64
                          https://conda.anaconda.org/formicidae-tracker/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bzniks/anaconda3/pkgs
                          /home/bzniks/.conda/pkgs
       envs directories : /home/bzniks/anaconda3/envs
                          /home/bzniks/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Linux/5.4.0-73-generic linuxmint/20.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

(RStudio_May2021) bzniks@LinuxMint:~$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(RStudio_May2021) bzniks@LinuxMint:~$ conda info

     active environment : RStudio_May2021
    active env location : /home/bzniks/anaconda3/envs/RStudio_May2021
            shell level : 2
       user config file : /home/bzniks/.condarc
 populated config files : /home/bzniks/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/bzniks/anaconda3  (writable)
      conda av data dir : /home/bzniks/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/formicidae-tracker/linux-64
                          https://conda.anaconda.org/formicidae-tracker/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bzniks/anaconda3/pkgs
                          /home/bzniks/.conda/pkgs
       envs directories : /home/bzniks/anaconda3/envs
                          /home/bzniks/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Linux/5.4.0-73-generic linuxmint/20.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

(RStudio_May2021) bzniks@LinuxMint:~$ conda config --set channel_priority strict
(RStudio_May2021) bzniks@LinuxMint:~$ conda install libfort-myrmidon
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \

**Comment by nathaliestroeymeyt** [comment]
I now realised that issue #192 dealt with the problem
In the meanwhile, I managed to install the packages by creating a new environment with python 3.7 and R 4.0. I am yet to test it, but will close the issue if it worked

**Comment by atuleu** [comment]
This is due to an incompatibility between `conda` `rstudio` package and `r-fort-myrmidon` dependencies.

However by installing rstudio using debian for example, and starting rstudio from the command line with an environment where `r-fort-myrmidon` is selected, everything is working, and the right version of R and `r-fort-myrmidon` is available.
