### ISSUE TITLE
Wrong ant1.trajectory.end and ant2.trajectory.end indices in output from fmQueryComputeAntInteractions ()

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/myrmidon#199]
In the interactions data.frame output from fmQueryComputeAntInteractions (), ant1.trajectory.start and ant2.trajectory.start seem correct, but ant1.trajectory.end and ant2.trajectory.end seem incorrect. 

Basically, even for very short interactions the difference between ant1.trajectory.start and ant1.trajectory.end (and between  ant2.trajectory.start and ant2.trajectory.end) is too large (sometimes a difference of c. 200 for an instantaneous interaction).

When using ant1.trajectory.row and ant1.trajectory.start to extract the starting time/coordinates from the trajectories and summaryTrajectory objects, the output matches the time displayed in the interactions data.frame, but that is not the case when using ant1.trajectory.row and ant1.trajectory.end to extract the ending time/coordinates from the trajectories and summaryTrajectory objects.

I have prepared a reproducible example to illustrate this and tried to upload it here, but I think the upload failed - instead you should be able to download the reproducible example from this link: https://www.dropbox.com/s/h5cnpbm2f5hi0ln/reproducible_example.tar.gz?dl=0
The example is within the illustration.R file, Issue 2 
(NB: Issue 1 was meant to illustrate that fmQueryComputeAntInteractions makes R crash when reportTrajectories=F, but I think that this is an already open issue).

**Comment by atuleu** [comment]
Yes I found the root of this bug after a complete rewrite of both the AntInteraction building algorithm and of all the unit test. The fix should come soon.
