### ISSUE TITLE
Fort-Studio: add an option to sort/filter by metadata Column in the Visualization workspace

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/myrmidon#201]
When visualizing data, it is sometimes useful to display groups of ants in different colours; e.g. ants that survived until the end of the experiment vs. ants that lost their tags/died at some point; or nurses vs foragers.

In large colony, it becomes difficult to assign colour individual per individual, and in the case of nurses vs forager, it is easy to make mistakes.

Hence it would be useful to be either able to filter the ants for different values of a particular metadata column - or alternatively, to display a metadata column next to the Hidden and Solo columns so we can sort the ants depending on their values for this particular column.

This would make life a lot easier to then assign specific colours to a group, or even to hide groups of ants with the same properties.

**Comment by atuleu** [comment]
I am not in favor to implement this:
* It is not trivial to implement this in the GUI
* It will clutter windows space for specific usage

On the other hand, color for an Ant is assignable by myrmidon. While dealing with large colony, one can assign the color it wants from any C++,R and python script and reopen the myrmidon file.
