### ISSUE TITLE
add a a new Matcher to check for moved distance during gaps.

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/myrmidon#202]
In previous versions of the tracking analysis, when there was an interruption in collisions between two particular ants, we relied on both a time threshold and a distance threshold to determine whether collisions on either side of the interruption were part of the same interaction or belonged to different interactions.

Basically, to be part of the same interaction the interruption needed to last less long than the time threshold and simultaneously the interacting ants needed to have moved by less than a threshold distance (in pixels). This allowed to defined a more permissive time threshold for ants that were inactive, without wrongly "merging" collisions that clearly should have belonged to a different interactions because both ants had moved a significant amount during the interruption.

At the moment, unless I am wrong, only the time threshold is implemented in the argument maximumGap.

For consistency and comparison with previous analyses, would it be possible to implement a distance gap as well? Instead of it being in mm or pixels, we could have this threshold a expressed as in tag sizes (e.g. if you enter a distance threshold of 3, that would mean that if either ant had moved by more than 3*their tag size, the collisions on either side of the interruption should be considered as belonging to different interactions).

**Comment by atuleu** [comment]
Please look at  [`fort::myrmidon::Matcher`](https://formicidae-tracker.github.io/myrmidon/docs/latest/api/#fort::myrmidon::Matcher/fort::myrmidon::Matcher), you can add specific matcher expression that let you build more complex queries.

**Comment by nathaliestroeymeyt** [comment]
As far as I understand the AntDistanceSmallerThan and AntDistanceGreaterThan from the fmMatcher are implemented as a condition on the distance between the two ants in a given frame, to determine whether or not they are in a collision on that frame.

That is different from what I have in mind which is about how to "merge" collisions into specific interactions. For many of our networks we use the number of interactions as an edge weight, so being able to tell apart different interactions is important.

At the moment this is controlled only by the maxGap parameter (at least I think?): if two ants are seen in contact in a given frame, then not in contact for a duration which is longer than maxGap, then in contact again, then 2 different interaction lines will be created in the output (we consider the duration of the interruption too long for iot to be the same interaction event).

However in the previous version we also had a condition on distance for this: if two ants were in contact, then not in contact, then in contact again - and either of these ants had moved by more than a certain distance during the interruption - then regardless of the duration of the interruption, it was considered that these were two different interactions. 

That's what I'm talking about here: creating a new interaction line in the interaction output when the distance moved by either ant is greater than a threshold value - and I don't think that's what AntDistanceSmallerThan and AntDistanceGreaterThan do...?
