### ISSUE TITLE
Fort-Studio documentation: link to online documentation broken

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/myrmidon#203]
In the vignette of the RStudio package, the link to the Fort Myrmidon C++ API documentation leads to https://formicidae-tracker.github.io/studio/docs/latest/api/ , which is no longer a valid link

**Comment by atuleu** [comment]
Will be solved in the next release as now the full documentation has been translated to the R package. So such links will not appear anymore in the next release
