### ISSUE TITLE
Incorrect tracking data video overlay in Visualization tab

### ISSUE THREAD

**Issue by matthiasruegg** [formicidae-tracker/myrmidon#211]
Inconsistent coordinates of displayed shapes with actual ant locations in the video, potentially from a wrong timestamp.

The issue is reproducible with different experiments and fort-studio version v0.7.4+git235.b9a2951, rev9 and *not* present with v0.7.4, rev8 on snap.

**Screenshots**
![image](https://user-images.githubusercontent.com/44613240/140508577-4d0df293-6410-450a-977d-ead5c2bd41e5.png)

**Affected packages**
`fort-studio` installed from  `snap`

**Installed version**
v0.7.4+git235.b9a2951 rev 9

As a quick fix therefore:
```sh
sudo snap revert fort-studio
```

**Comment by atuleu** [comment]
Not present in v0.7.3
