### ISSUE TITLE
Option in Fort Myrmidon to allow interactions to occur between zones

### ISSUE THREAD

**Issue by MO-Katy** [formicidae-tracker/myrmidon#216]
At the moment interactions can't occur when the two individuals are in different zones, which is good when the zone is a nest with walls. But it would be useful to use the zoning feature to define areas of the arena different for behavioural analysis - e.g., where is the trash pile, where is the brood.

For that it would be important that when an individual is within one zone it can still interact with an individual just outside of that zone. Could that be added as an option?

**Comment by atuleu** [comment]
Sure, it could be added for version 0.8.1 as it is fearly simple.
