### ISSUE TITLE
Question: FortMyrmidon v0.8.0 on R?

### ISSUE THREAD

**Issue by nathaliestroeymeyt** [formicidae-tracker/myrmidon#222]
Is FortMyrmidon version 0.8.0 available on R? 

I created a new conda environment and installed libfort-myrmidon and r-fort-myrmidon using conda, but when loading library(FortMyrmidon) in R from this new environment it seems it is still version 0.7.3 (I checked using help and using packageVersion, both say the same)...I don't know if I did something wrong or if versions 0.7.4 and 0.8.0 are simply not available for R yet...?

Any help would be much appreciated!

Thanks,
Nathalie

**Comment by atuleu** [comment]
```bash
$ conda search -c formicidae-tracker r-fort-myrmidon
Loading channels: done
# Name                       Version           Build  Channel             
r-fort-myrmidon                0.7.2   r36h3fd9d12_0  formicidae-tracker  
r-fort-myrmidon                0.7.2   r40h3fd9d12_0  formicidae-tracker  
r-fort-myrmidon                0.7.3   r36h3fd9d12_0  formicidae-tracker  
r-fort-myrmidon                0.7.3   r40h3fd9d12_0  formicidae-tracker  
r-fort-myrmidon                0.8.0   r40h7bfd51e_0  formicidae-tracker  
```
So yes `r-fort-myrmidon` is deployed for v0.8.0 on the `formicidae-tracker` channel. Please note that support for R 3.6 has been dropped ( you only see `r40XXXXXX` variants).

You can ask `conda` to install a specific version with:
```bash
$ conda install r-fort-myrmidon=0.8.0
```

Please also consider installing `mamba` (a much faster replacement` for `conda`) to install this package
```bash
conda deactivate
conda install -c conda-forge mamba
mamba create -n my-env-name -c formicidae-tracker r-fort-myrmidon=0.8.0
conda activate my-env-name
rstudio
```
