### ISSUE TITLE
Ant Metadata Workspace not working

### ISSUE THREAD

**Issue by AdrianoWanderlingh** [formicidae-tracker/myrmidon#236]
**Describe the bug**
in v0.8.1, Ant Metadata Workspace is missing some elements as the section ‘Timed changes for Ant xxx’. It is possible to edit the metadata column directly by changing the Value provided as default but it is not possible to add the timed change. Opening the file in 0.7.2 shows the edited value in black instead of blue and the all column can't be deleted from the section "Column definition". 

**To Reproduce**
1. go to the Ant Metadata Workspace>Column definition and click ‘+’ to create a new column. 
2. Then double click on the individual that has lost the tag to access the ‘Timed changes for Ant xxx’ section

**Affected packages**
Please select one or more package by putting a `x` in the brackets

- [ ] `libfort-myrmidon` installed from `conda`
- [ ] `py_fort_myrmidon`installed from `conda`
- [ ] `r-fort-myrmidon` installed from `conda`
- [x] `fort-studio` installed from  `snap`
- [ ] `fort-studio` installed from `conda`

**Installed version**
v.0.8.1

**Comment by atuleu** [comment]
The manual does not describe extensively on how to use the new GUI, but :
* To set the base value for a Key, simply edit the value next to the key name, under the desired Ant.
* to add a timed value, select the corresponding key line under the desired Ant, and click the add button. You will need to expand the sub-item tree. Now you can sets the desired values and time.

There are no blue indication anymore. If an Ant base value is the default one it will appear as 'default (<default_value>) next to the key name
