### ISSUE TITLE
Update tag-scanner to load myrmidon 0.3.0

### ISSUE THREAD

**Issue by AdrianoWanderlingh** [formicidae-tracker/myrmidon#243]
**Is your feature request related to a problem? Please describe.**
Couldn't load a myrmidon file version 0.3.0 with the latest version of tag-scanner (installed through snap). 

**Describe the solution you'd like**
tag-scanner update

**extra**
Would be very useful to have an extra column for notes in the "data" section of the scanner (adding and naming notes columns has to be done in a text editor outside the scanner currently).

**Comment by atuleu** [comment]
It seems an issue related to tag-scanner, not fort-myrmidon.
