### ISSUE TITLE
Ghost ants

### ISSUE THREAD

**Issue by MO-Katy** [formicidae-tracker/myrmidon#245]
If an ant is created in Fort Studio, and then deleted, when the .myrmidon file is read by the python bindings the deleted ID still appears as an ant.

When we query interactions for a period of time in which the deleted ant had been identified it results in a runtime error. 

RUNTIME ERROR: Ant XXX is not identified.

**Affected packages**
Please select one or more package by putting a `x` in the brackets

- [ ] `libfort-myrmidon` installed from `conda`
- [x] `py_fort_myrmidon`installed from `conda`
- [ ] `r-fort-myrmidon` installed from `conda`
- [x] `fort-studio` installed from  `snap`
- [] `fort-studio` installed from `conda`

**Installed version**
Fort-Studio v0.8.2
py_fort_myrmidon v0.8.1

**Comment by atuleu** [comment]
Could you provide some complete code example ?

**Comment by MO-Katy** [comment]
import py_fort_myrmidon as fm
from datetime import datetime, timedelta
import numpy as np
import pandas as pd 

f_myrmidon = "/media/work1/Alba/Rhytio_col2.2.myrmidon"
exp = fm.Experiment.Open(f_myrmidon)
t_start = datetime(2022, 4, 11, 0, 1).astimezone(tz=None)
t_end = datetime(2022, 4, 16, 18, 0).astimezone(tz=None)

df_metadata = pd.DataFrame(index=exp.Ants)
df_metadata["tag_id"] = np.nan
for ant in exp.Ants:
    df_metadata.loc[ant, "tag_id"] = exp.Ants[ant].IdentifiedAt(fm.Time(datetime(2022, 4, 11, 18, 30).astimezone(tz=None)))

**Comment by MO-Katy** [comment]
If we run exp.DeleteAnt(ant) for the ID which throws the error then the problem is gone when the code is re-run

**Comment by atuleu** [comment]
How did you " Delete the Ant" in fort studio. Did you actually deleted the Ant, by removing it from the list of ants, or did you just remove the Identification to the ant.

If you can `fm.Experiment.DeleteAnt()` without error, it means that the Ant object is still present (check the global Ant list in fort-studio). I think you only removed the identification in the Identification list of the Identification workspace.

**Comment by atuleu** [comment]
Another comment : avoid at all cost to use `fm.Time(datetime().astimezone(tz=None))` in your code. Here you are creating a time in the local timezone and manually convert it to UTC, which is bad for two reasons :
* You need to tale into account UTC - localtime change when comparing timestamp between your code and fort-studio
* If you forgot the `.astimezone(tz=None)` conversion, the localtime will be taken as UTC without proper conversion which may lead to unexpected time offset.
You should rather specify `fm.Time.Parse("2022-04-11T16:30:00.000Z")`. Note that here, the timestamp can be copied from fort-studio.

**Comment by MO-Katy** [comment]
Yes exactly. I just deleted the row in the identifications tab. How do I remove it from the list of ants in fort studio?

And thanks for the time thing

**Comment by atuleu** [comment]
You can remove them using the "-" button in the ant listing ( enabled after clicking on the ant you want to remove)

**Comment by MO-Katy** [comment]
Okay sorry I was deleting the identification but not the ant. Resolved!
