### ISSUE TITLE
Error with addTrackingDataDirectory()

### ISSUE THREAD

**Issue by d-schlaeppi** [formicidae-tracker/myrmidon#250]
When trying to add a tracking directory to a myrmidon file in R using addTrackingDataDirectory() from R bindings we encountered the following error: 

> tracking_data$addTrackingDataDirectory(s$ID, paste0(directory, folder_name))

Error in tracking_data$addTrackingDataDirectory(s$ID, paste0(directory,  : 
  could not find valid method

Is there another method that we should use, is it a bug or is it just me not understanding what I am doing?

**Comment by atuleu** [comment]
In the latest version of the R bindings, `fmExperiment$addTrackingdataDirectory()` takes an additional `fixCorruptedData` argument.

The way the `rcpp` package works (the package that allows a R program to interface with C++), if you fail to provide all needed arguments, it returns this very cryptic method, which does not tell you to add the missing value.

To get the old behaviorm please use FALSE, and the call will fail if there is a data corruption. Use `TRUE` to ask to not fail but try to fix any encountered error (will cause permanent data loss, but let you recover as much data as possible).
