### ISSUE TITLE
Mac installation 

### ISSUE THREAD

**Issue by MO-Katy** [formicidae-tracker/myrmidon#59]
std::variant is apparently incompatible with Mac OS 10.13

**Comment by matthiasruegg** [comment]
This problem seems to be related to [that discussion](https://stackoverflow.com/questions/52521388/stdvariantget-does-not-compile-with-apple-llvm-10-0). The problem appear with macOS 10.13. It is worth trying with a newer OS version.

**Comment by atuleu** [comment]
Hi, as says in the prerequisite, you will need a fully c++17 compiler.

Apple has the very bad habit to use it's own versionning for clang and llvm, and does not use consistent version between the compiler and the runtime. Meaning you can compile five, but you may miss symbols...

Apparently full c++17 support was added to 10.15, as filesystem leaved experimental/filesystem in Xcode11 but is only available on 10.15. 

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes?preferredLanguage=occ

**Comment by MO-Katy** [comment]
Okay, thanks. My mac is a bit broken and won't upgrade the OS. I was already thinking about getting a new one...

**Comment by atuleu** [comment]
@MO-Katy 
So there are some work in the dev/macos branch however:
* Some tests are failing so we may have some really hard crash of the software
* There are no icons for buttons (really apple T-T)
* Things may breaks more often. Indeed clang (the compiler apple uses) is much more strict in term of header order. So even if I merge the dev/macos branch, new development in the other branch may break easily on macOS.... Not sure I want to fully support macOS (I use a virtual machine at the moment)
* Only mojave and up are supported, and maybe in a year only catalina and up

**Comment by atuleu** [comment]
Could be of some use: https://github.com/formicidae-tracker/studio/blob/dev/macos/docs/macOS.md

**Comment by atuleu** [comment]
Since now everything is packaged with conda and snap, we are kind of locked up to support only linux installation (but kind of any distro).

Furthermore, apple is going full arm, and an arm64 port may not be trivial.

In other word, macOS support for this small project may too much to ask.
